services:
  mmu_rag_lite:
    build:
      context: ../..
      dockerfile: Dockerfile.lite
    container_name: mmu-rag-lite
    ports:
      - "8900:8900"
    restart: always
networks:
  # docker network create ase_backend
  ase_backend:
    external: true